### ISSUE TITLE
疑似签名人数与显示人数不匹配？

### ISSUE THREAD

**Issue by Lafcadia** [LGBT-CN/LGBTQIA-In-China#331]
“实际人数”（签名区行数）为206 (37-242)，但是README.md上显示有229人签署？owo?
![image](https://github.com/LGBT-CN/LGBTQIA-In-China/assets/147896059/d79c2fb8-48ce-4940-84fb-1d14d68939b1)

**Comment by KevinZonda** [comment]
Good question!

**Comment by gxres042** [comment]
我有一个猜想。近期有一些更名的 PR，而 Action 很有可能将它们当作了新署名的 PR。所以这些更名的 PR 合并后会继续向上叠人数hh

**Comment by KevinZonda** [comment]
> 我有一个猜想。近期有一些更名的 PR，而 Action 很有可能将它们当作了新署名的 PR。所以这些更名的 PR 合并后会继续向上叠人数hh

Nah, 代码是统计 \n 而不是根据commit的

**Comment by KevinZonda** [comment]
I will rewrite the counting procedure. :)

**Comment by KevinZonda** [comment]
Hi I fixed the problem. The issue is caused by incorrect end tag `<!-- 结束LGBT-CN 签名 -->`, proper one should be like `<!-- END LGBT-CN SIGNATURE -->`. I rewrite the counter a little bit. Make it more robust. When such happened again, the counter application will panic so we can get when such situation happened again.
